In [1]:
import pandas as pd
import numpy as np

from sklearn.linear_model import LinearRegression

In [2]:
pd.read_csv("50_Startups.csv").head()

   R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99
4  142107.34        91391.77        366168.42     Florida  166187.94

In [3]:
df=np.round(pd.read_csv("50_Startups.csv",usecols=['R&D Spend','Administration','Marketing Spend','Profit'])/10000)

In [4]:
np.random.seed(10)  # it is use to produce same sample data having seed value 10
df.sample(5)

    R&D Spend  Administration  Marketing Spend  Profit
37        4.0             5.0             20.0     9.0
23        7.0            11.0             30.0    11.0
44        2.0            15.0              3.0     7.0
42        2.0            10.0             15.0     7.0
47        0.0            14.0              0.0     4.0

In [5]:
df=df.head(5)
df=df.iloc[:,0:3]
df

   R&D Spend  Administration  Marketing Spend
0       17.0            14.0             47.0
1       16.0            15.0             44.0
2       15.0            10.0             41.0
3       14.0            12.0             38.0
4       14.0             9.0             37.0

In [6]:
df.iloc[1,0]=np.nan
df.iloc[3,1]=np.nan
df.iloc[-1,-1]=np.nan

In [7]:
df.head()

   R&D Spend  Administration  Marketing Spend
0       17.0            14.0             47.0
1        NaN            15.0             44.0
2       15.0            10.0             41.0
3       14.0             NaN             38.0
4       14.0             9.0              NaN

In [8]:
# Step 1 - Impute all missing values with mean of respective col

df0=pd.DataFrame()

df0=df.copy()
df0

   R&D Spend  Administration  Marketing Spend
0       17.0            14.0             47.0
1        NaN            15.0             44.0
2       15.0            10.0             41.0
3       14.0             NaN             38.0
4       14.0             9.0              NaN

In [9]:
nan_postions_rows,nan_postions_columns=np.where(df0.isnull())
nan_postions_rows

array([1, 3, 4])

In [10]:
# df0['R&D Spend'].fillna(df0['R&D Spend'].mean(),inplace=True)

df0.fillna(df0.mean(),inplace=True)

In [11]:
df0

   R&D Spend  Administration  Marketing Spend
0       17.0            14.0             47.0
1       15.0            15.0             44.0
2       15.0            10.0             41.0
3       14.0            12.0             38.0
4       14.0             9.0             42.5

In [12]:
df1=df0.copy()
df1.iloc[nan_postions_rows[0],nan_postions_columns[0]]=np.nan
df1

   R&D Spend  Administration  Marketing Spend
0       17.0            14.0             47.0
1        NaN            15.0             44.0
2       15.0            10.0             41.0
3       14.0            12.0             38.0
4       14.0             9.0             42.5

In [13]:
# Use first 3 rows to build a model and use the last for prediction

# X=df.iloc[!df]
not_nan_rows = df1[df1.notna().all(axis=1)].index.tolist()

X=df1.iloc[not_nan_rows,1:3]
X

   Administration  Marketing Spend
0            14.0             47.0
2            10.0             41.0
3            12.0             38.0
4             9.0             42.5

In [14]:
y=df1.iloc[not_nan_rows,0]
y

0    17.0
2    15.0
3    14.0
4    14.0
Name: R&D Spend, dtype: float64

In [15]:
lr=LinearRegression()
lr.fit(X,y)
lr.predict(df1.iloc[nan_postions_rows[0],1:].values.reshape(1,2))

C:\Users\vk704\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([16.5625])

In [16]:
df1.iloc[1,0]=16.56

In [17]:
df1

   R&D Spend  Administration  Marketing Spend
0      17.00            14.0             47.0
1      16.56            15.0             44.0
2      15.00            10.0             41.0
3      14.00            12.0             38.0
4      14.00             9.0             42.5

In [18]:
df1.iloc[nan_postions_rows[1],nan_postions_columns[1]]=np.nan

In [19]:
df1

   R&D Spend  Administration  Marketing Spend
0      17.00            14.0             47.0
1      16.56            15.0             44.0
2      15.00            10.0             41.0
3      14.00             NaN             38.0
4      14.00             9.0             42.5

In [22]:
not_nan_rows=df1[df1.notna().all(axis=1)].index.tolist()
not_nan_rows

[0, 1, 2, 4]